services:
  app:
    image: node:24
    container_name: aluno-online-react
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: aluno_online_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aluno_online
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

volumes:
  db_data: