name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Backend
        run: |
          cd aluno-online-react/backend
          npm install

      - name: Testar Backend
        run: |
          cd aluno-online-react/backend
          npm test

      - name: Instalar Frontend
        run: |
          cd aluno-online-react/frontend
          npm install

      - name: Testar Frontend
        run: |
          cd aluno-online-react/frontend
          npm test

      - name: Build Frontend
        run: |
          cd aluno-online-react/frontend
          npm run build